### ISSUE TITLE
[My Campaigns] The sorting is incorrect

### ISSUE THREAD

**Issue by jiewsone** [coa0329/Bhaang#93]
We have sort campaign by field "lastEditDate", but it's sort by String in that field.
Ex. 
{campaignName:'cp1',lastEditDate:'Wed, 06 Sep 2017 04:40:42 GMT'}
{campaignName:'cp2',lastEditDate:'Thu, 07 Sep 2017 04:02:59 GMT'}
{campaignName:'cp3',lastEditDate:'Tue, 05 Sep 2017 07:19:37 GMT'}

The correct should be
{campaignName:'cp2',lastEditDate:'Thu, 07 Sep 2017 04:02:59 GMT'}
{campaignName:'cp1',lastEditDate:'Wed, 06 Sep 2017 04:40:42 GMT'}
{campaignName:'cp3',lastEditDate:'Tue, 05 Sep 2017 07:19:37 GMT'}

Now, It's sort like this
{campaignName:'cp1',lastEditDate:'Wed, 06 Sep 2017 04:40:42 GMT'}
{campaignName:'cp3',lastEditDate:'Tue, 05 Sep 2017 07:19:37 GMT'}
{campaignName:'cp2',lastEditDate:'Thu, 07 Sep 2017 04:02:59 GMT'}

Kwang will take care this bug.

**Comment by paweenwich** [comment]
Done. 

change data in couchDB into ISO 8601 format.  
Ex  2017-08-29T16:20:16Z

**Comment by daver78** [comment]
@paagla123 will you verify this fix before we close?

@paweenwich so I'm clear, the couchDB timestamp is based on any change the User has made in the Da Vinci UI, not a change that was published to Studio.  Correct?

**Comment by daver78** [comment]
@paagla123 and @paweenwich I'm not sure this is working anymore.  I haven't had time to dig into it.  Previously, it seemed to be OK but with whatever we changed here, the behavior doesn't seem right (that is, I make an edit, and expect to see my Campaign at the top of the list now; however, it shows up as edited 12 hours ago or more).  

Am I missing something?

**Comment by paweenwich** [comment]
@daver78 timestamp record time that save in DV UI.   I will check this issue again.

**Comment by daver78** [comment]
@paweenwich OK, thanks for the info on `lastEditDate`. Let me know if you find an issue somewhere.

**Comment by coa0329** [comment]
@paweenwich  fixed it.

**Comment by daver78** [comment]
@paweenwich and @coa0329 are you sure?  Did you push this to web2xmm?

The behavior seems the same to me, but I need @paagla123 to verify I'm not going crazy.

**Comment by paagla123** [comment]
Its using the last edit timestamp for sure. However, it is also putting it in a strange timezone it seems, which is 12 hours ahead of Pacific time - could be Indian Standard Time. Please correct this. Updates I did just now show up as "updated 12 hours ago". Pl see screenshot.

![image](https://user-images.githubusercontent.com/29718335/30225863-d681f25e-9488-11e7-8aa2-fc049942317f.png)

**Comment by paagla123** [comment]
Time stamp is 12 hours off. Its ahead by 12 hours.

**Comment by daver78** [comment]
@paagla123 and @paweenwich, I commited to GIT the following change in `welcome.php` and `myCampaigns.php`:

```
<!-- Roll back to this <span am-time-ago="message.time"></span> -- once timestamp issue is resolved -->
<small>Modified {{item.lastEditDate | amUtc | amLocal | amAdd : '12' : 'hours' | amDateFormat:'MMMM Do YYYY, h:mm a'}}</small>

```
You can see it here: [http://da-vinci-core-daver438618.codeanyapp.com/admin/welcome.php](http://da-vinci-core-daver438618.codeanyapp.com/admin/welcome.php)

We should pull this to web2xmm server until we fix it.  Once we fix it, we should then roll back to the previous snippet.

**Comment by paagla123** [comment]
@paweenwich pl discuss with me Monday 11AM BKK time. Dave made changes to hide the problems - we will need a permanent fix and merge code. Thx

**Comment by paweenwich** [comment]
Let me explain, 
Right now, the lastEditDate is in UTC/GMT (same time) ISO 8601 format.  
Ex 2017-08-29T16:20:16Z

The reason for this is, Angular + IE can not handle time zone correct;y.   For example, if we put something  like "06-08-2017 04:40:42 GMT"   am-time-ago will show as "Invalid date".     StackExchange suggested to use ISO 8601 format.   

The I think that if we are going to use am-time-ago, we might now need to care about the timezone.  So, I use standard GMT time zone instead of PST/PDT.   

I have no idea why if off 12 hour when convert to local time, I will play with this.

**Comment by paweenwich** [comment]
Please check  

https://codepen.io/muminoi/pen/ZJPjKv?editors=1011

RAW Date is date format that we might want put into DB

Loc time is display date when using {{item.lastEditDate | amDateFormat:'MMMM Do YYYY, h:mm a'}}

Loc time + 12 is what we currently using {{item.lastEditDate | amUtc | amLocal | amAdd : '12' : 'hours' | amDateFormat:'MMMM Do YYYY, h:mm a'}}

time ago is <span am-time-ago="item.lastEditDate"></span>

Add time will add current time (simulate when we update campaign)

*In IE,  for GMT PST, angular will show empty string or "Invalid date"



RAW Date is date format that we might want put into DB

Loc time is display date when using {{item.lastEditDate | amDateFormat:'MMMM Do YYYY, h:mm a'}}

Loc time + 12 is what we currently using {{item.lastEditDate | amUtc | amLocal | amAdd : '12' : 'hours' | amDateFormat:'MMMM Do YYYY, h:mm a'}}

time ago is <span am-time-ago="item.lastEditDate"></span>

Add time will add current time (simulate when we update campaign)

*In IE,  for GMT PST, angular will show empty string or "Invalid date"

**Comment by daver78** [comment]
@paagla123 I see that you discussed with @paweenwich and said you speak to me about this.  I'll try you in a few hours if possible.

**Comment by paagla123** [comment]
@paweenwich this is still not correct. See screenshot below - I just modified this campaign and it shows 12 hours ago!
![image](https://user-images.githubusercontent.com/29718335/30284080-cc68ab6c-96ce-11e7-8405-8a408cc5105a.png)

**Comment by paweenwich** [comment]
@paagla123   As I told you, my either my demo code in codepen or Dave's fixed (add 12 hours) is correct.  How come that when we chat yesterday you said it work, and later you say it does not, while we have not touch any code or data on that machine.    Let's check this together again in today chat.  :)

**Comment by paagla123** [comment]
@paweenwich no idea. We will look together today. Thx

**Comment by paagla123** [comment]
@daver78 @paweenwich this worked fine last night, today morning and now. So I am going to assume that some IT has fixed it and close it.Thanks for all your patience.

**Comment by daver78** [comment]
Hooray!!

**Comment by paagla123** [comment]
Reopened. Production again says 12 hours instead of a few seconds. Staging has some issues as well. Let us fix in Staging.

**Comment by paagla123** [comment]
The createdate and lasteditdate in DBView are both wrong - that is the problem. When I create or edit a campaign at 1045AM PST on 9/15, it shows 2017-09-15T05:45:00Z, whereas it should really show 2017-09-15T17:45:00Z. Because of this we see the 12 hour time difference. @paweenwich can we please fix now? Thx

**Comment by paagla123** [comment]
Per Dave:
![image](https://user-images.githubusercontent.com/29718335/30498305-ff31a38e-9a0a-11e7-851f-e72cbfa12e84.png)

**Comment by daver78** [comment]
@paweenwich I would add:

`date_default_timezone_set("UTC");`

... anywhere you do something like this:

`$dateTimeNow = gmdate('Y-m-d\TH:i:s\Z', time()); `

I think there is a known issue with `gmdate` if the server is in a timezone other than UTC.

**Comment by paagla123** [comment]
@paweenwich this is completely messed up in Staging now. Shows local machine's date and time without a time zone. I created a campaign at 6:04PM - shows Sept 17 6:04PM. I changed time zone of my local machine to Eastern and updated - shows Sept 17 9:05PM. I switched back to Pacific time and updated again, shows Sept 17 6:06PM.

**Comment by paweenwich** [comment]
Assuming we keep data in DB as UTC correctly.  
@paagla123 When you see the time in UI,  typically, without time zone indicated, it should show time according to your computer time zone.   That is why 
" I created a campaign at 6:04PM - shows Sept 17 6:04PM. I changed time zone of my local machine to Eastern and updated - shows Sept 17 9:05PM. "

This is correct behavior.  If you don't want this, you need to tell me which time zone you want the UI to display. 

Done means done in stage.  So, the production problem which is more than 10 commit behind stage is old issue.    If we can not make stage work correctly, we should leave production as it right now and focus on fixing the stage.  

So, please make sure we are talking about staging.  

I am checking this problem again.  May need your demo on problem when we have a call to day.   Dave suggestion also looks promising.

**Comment by paagla123** [comment]
@paweenwich I am testing only in Staging now - items that are in the project called Fixed in Staging have passed testing in Staging and are ready for production release. After production release, I will test them in production again and close the issues if fixed in production. So all testing refers to Staging now.

@paweenwich please store time stamp in UTC and use Angular Moment to display the time.

**Comment by paweenwich** [comment]
Done (Put save suggestion on the code and put angular-moment back to myCampaign).

**Comment by paagla123** [comment]
Fixd in Staging. Thx

**Comment by daver78** [comment]
@paweenwich and @paagla123 How did we end up fixing this??

**Comment by paagla123** [comment]
@paweenwich NOT FIxed. I created two campaigns this morning around 1030AM PST. Shows CouchDB data as 
{
           "campaignID": "c7784cd5018e06211e161a6c5a3baf88",
           "accountID": "16916",
           "campaignName": "KD-0919-Oncology",
           "createDate": "2017-09-19T05:24:48Z",
           "lastEditDate": "2017-09-19T05:27:56Z",
           "status": "Edit",
           "campaignType": "PromoteBlog"
       },
       {
           "campaignID": "449f1dafc8355806ac9ec5ad114cae10",
           "accountID": "16916",
           "campaignName": "KD-0919-Cardiology",
           "createDate": "2017-09-19T05:29:25Z",
           "lastEditDate": "2017-09-19T05:29:25Z",
           "status": "Edit",
           "campaignType": "PromoteBlog"
       }

Display in My Campaigns:
![image](https://user-images.githubusercontent.com/29718335/30618697-6f588d92-9d50-11e7-940b-d5c6a0b6e190.png)

Yesterday the display was different.

**Comment by paagla123** [comment]
@paweenwich This is still messed up - in fact gotten worse in Staging
![image](https://user-images.githubusercontent.com/29718335/30725329-d714ff66-9ef8-11e7-81bd-8ce4770ca5d1.png)

![image](https://user-images.githubusercontent.com/29718335/30725338-f0116db0-9ef8-11e7-9b2a-edf52c5ef3ee.png)

**Comment by daver78** [comment]
@paagla123 What do you mean "worse"?  It's either right or wrong.  I didn't know there are degrees of righness and wrongness here :)

**Comment by paagla123** [comment]
@paweenwich @coa0329 I do not know why this cannot be fixed. The issue is crystal clear to me. The Zulu time calculation does not account for AM or PM. I edited this campaign at 1220PM Pacific time. See what couchDB has - 07:20:10Z. I went to zulutime.net and it shows 19:20:10 - pl see screenshots below. The reason you can never reproduce this issue is because you are always ahead of Zulu time. If you test this issue any day after 7PM Bangkok time, you will catch it, because that is past noon Zulu time. Pl check, reproduce and fix ASAP. Thx

![image](https://user-images.githubusercontent.com/29718335/30760955-4e0f9778-9f91-11e7-8b6c-a69b75e2652f.png)

![image](https://user-images.githubusercontent.com/29718335/30761004-9b4df4ee-9f91-11e7-9ca3-28618ded448d.png)

**Comment by daver78** [comment]
@paagla123 and @paweenwich I have no idea what the heck ZULU time is, but I know what the problem is.  I already told @paagla123 how to solve this!

Whoever wrote the function for the `datetime` has `hh` instead of `HH`.

I'll look for it in the code and fix it.

**Comment by daver78** [comment]
Ok, this should do it.  `davinci.js` is the culprit, and whoever wrote this line:

![image](https://user-images.githubusercontent.com/7561473/30763635-0fb98cd0-9f9c-11e7-90e9-6b519f77b8ef.png)

**Comment by paagla123** [comment]
@daver78 that is exactly the point. @paweenwich wanted to know why he can never reproduce it. He can only reproduce it if he tests it after 7PM Bangkok time. Do the math!

**Comment by daver78** [comment]
@paagla123 OK you win!  I'll give you a prize :)

Anywho, let's make sure this actually fixes it before we celebrate.  Please confirm (pull to your dev machine or wait until it is deployed to staging).

**Comment by paagla123** [comment]
@daver78 @paweenwich I will test tomorrow and let you know. I have to test after 5AM PST to reproduce it.

**Comment by daver78** [comment]
@paagla123 How are you going to test?  Do you pull it to your own environment?

**Comment by paweenwich** [comment]
@daver78 I did that line :(

**Comment by daver78** [comment]
@paweenwich Ha!  No worries :)  Before we celebrate let's make sure @paagla123 confirms it is actually working.  I suspect it should be fine now, but let's see.

**Comment by paagla123** [comment]
@daver78 @paweenwich not fixed - did anyone overwrite .js changes by Dave?

**Comment by paagla123** [comment]
@paweenwich this is fixed. Please assign someone to get the angular moment code set up correctly in the display. We can then retest and move this to prod this week.

**Comment by paweenwich** [comment]
@paagla123 you mean, remove the exact date time, so it  show only "xxxx hours agao".  Is this correct?

**Comment by paagla123** [comment]
@paweenwich yup!
